title: "Xinyu Su (Suzy)"
description: "
  Ph.D., The University of Melbourne
  Postdoctoral Researcher @ Fudan University
  Spatial-temporal forecasting | FuXi Group"
theme: jekyll-theme-minimal
logo: /assets/profile.jpg

# --- Add this section ---
show_downloads: false
github_username: suzy0223
email: sxy96223@gmail.com
google_scholar: "https://scholar.google.com.au/citations?user=2am36BUAAAAJ&hl=zh-CN"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: /:title/
