title: "Xinyu Su (Suzy)"
description: "Recevied Ph.D. degree from The University of Melbourne"
theme: jekyll-theme-minimal
logo: /assets/profile.jpg

# --- Add this section ---
show_downloads: false
github_username: suzy0223
email: suxs3@student.unimelb.edu.au
google_scholar: "https://scholar.google.com.au/citations?user=2am36BUAAAAJ&hl=zh-CN"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: /:title/
